# Generated by Django 5.1.6 on 2025-02-20 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='explore_places',
        ),
        migrations.AddField(
            model_name='trip',
            name='explore_places',
            field=models.TextField(blank=True, null=True),
        ),
    ]
