# Generated by Django 4.2.21 on 2025-05-12 10:07

from django.db import migrations, models
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postimage',
            name='image',
            field=models.ImageField(upload_to='posts/', validators=[posts.models.validate_image_size]),
        ),
    ]
