# Generated by Django 4.2.21 on 2025-05-12 10:07

from django.db import migrations, models
import places.models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placeimage',
            name='image',
            field=models.ImageField(upload_to='places/', validators=[places.models.validate_image_size]),
        ),
    ]
