# Generated by Django 3.1.12 on 2025-02-16 19:41

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('img', models.ImageField(upload_to='places/')),
                ('description', models.TextField()),
                ('like', models.IntegerField(default=0)),
                ('nearby_city', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=255)),
                ('best_time_to_visit', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('distance_from_nearby_place', models.CharField(max_length=255)),
                ('rating', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('address', models.TextField(blank=True, null=True)),
                ('mobile_number', models.CharField(max_length=10, unique=True)),
                ('followers', models.JSONField(default=list)),
                ('follow', models.JSONField(default=list)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('DOB', models.DateField(blank=True, null=True)),
                ('role', models.CharField(default='user', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('profile_picture', models.ImageField(default='uploads/default-avatar.png', upload_to='uploads/')),
                ('profile_background', models.ImageField(default='uploads/default-avatar-bg.png', upload_to='uploads/')),
                ('groups', models.ManyToManyField(blank=True, related_name='custom_user_groups', to='auth.Group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='custom_user_permissions', to='auth.Permission')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('img', models.ImageField(upload_to='trips/')),
                ('destination', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('budget', models.IntegerField()),
                ('explore_places', models.JSONField(default=list)),
                ('itinerary', models.JSONField(default=list)),
                ('type', models.CharField(choices=[('private', 'Private'), ('public', 'Public')], max_length=10)),
                ('trip_members', models.ManyToManyField(related_name='trip_members', to='adminpanel.User')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='adminpanel.user')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('img', models.ImageField(upload_to='posts/')),
                ('caption', models.TextField()),
                ('like', models.IntegerField(default=0)),
                ('comments', models.JSONField(default=list)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.user')),
            ],
        ),
    ]
