# Generated by Django 3.1.12 on 2025-02-16 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterModelTable(
            name='place',
            table='places',
        ),
        migrations.AlterModelTable(
            name='post',
            table='posts',
        ),
        migrations.AlterModelTable(
            name='trip',
            table='trips',
        ),
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
    ]
