# Generated by Django 3.1.12 on 2025-02-18 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='itinerary',
            table='trip_itinerary',
        ),
        migrations.AlterModelTable(
            name='trip',
            table='trips',
        ),
    ]
