# Generated by Django 4.2.21 on 2025-05-17 18:50

from django.db import migrations, models
import trips.models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='tripimage',
            name='image',
            field=models.ImageField(upload_to='trips/', validators=[trips.models.validate_image_size]),
        ),
    ]
