# Generated by Django 4.2.21 on 2025-05-12 10:07

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_background',
            field=models.ImageField(blank=True, null=True, upload_to='profile_backgrounds/', validators=[users.models.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/', validators=[users.models.validate_image_size]),
        ),
    ]
